apiVersion: v2
name: mobile-app
version: 0.0.1-beta.1
description: Backend & backoffice for the Eurofurence mobile app including an optional home page and web-based back office UI.
keywords:
  - eurofurence
  - backend
  - mobile-app
home: https://app.eurofurence.org
sources:
  - https://github.com/eurofurence/ef-app_helm
  - https://github.com/eurofurence/ef-app_backend-dotnet-core
  - https://github.com/eurofurence/ef-app_react-native
maintainers:
  - name: Fenrikur
    url: https://github.com/fenrikur
icon: https://app.eurofurence.org/images/ef-app-logo.png
appVersion: "v3.6.0"
