## Global parameters that may be overridden per deployment
global:
  ## Source and policy for pulling container images
  image:
    repository: ghcr.io/eurofurence
    imagePullPolicy: IfNotPresent
  ## Version of mobile app backend to be deployed
  version: "v3.6.0"

ingress:
  ## Domain under which the backend will be hosted
  host: app.example.com
  ## (optional) Provide additional annotations for ingress.
  ## (e.g. for `cert-manager.io/cluster-issuer` or `nginx.ingress.kubernetes.io/…`)
  annotations:

## Allow use of Infisical (https://infisical.com) for secret management.
## Expects the following uppercase secret keys per deployment, prefixed by deployment identifier:
## - <deployment identifier all uppercase>_APPLE_APP_SITE_ASSOCIATION_JSON
##   (see https://developer.apple.com/documentation/xcode/supporting-associated-domains)
## - <deployment identifier all uppercase>_APPSETTINGS_JSON
##   (see https://github.com/eurofurence/ef-app_backend-dotnet-core/blob/main/src/Eurofurence.App.Server.Web/appsettings.sample.json)
## - <deployment identifier all uppercase>_APPSETTINGS_BACKOFFICE_JSON
##   (see https://github.com/eurofurence/ef-app_backend-dotnet-core/blob/main/src/Eurofurence.App.Backoffice/wwwroot/appsettings.sample.json)
## - <deployment identifier all uppercase>_ASSETLINKS_JSON_JSON
##   (see https://developer.android.com/training/app-links/verify-android-applinks)
## - <deployment identifier all uppercase>_FIREBASE_JSON
##   (see https://github.com/eurofurence/ef-app_backend-dotnet-core/blob/main/src/Eurofurence.App.Server.Web/firebase.sample.json)
infisical:
  enabled: true
  ## see https://infisical.com/docs/integrations/platforms/kubernetes/infisical-secret-crd#authentication-methods
  authentication:
    ## see https://infisical.com/docs/documentation/platform/identities/universal-auth
    universalAuth:
      secretsScope:
        projectSlug: mobile-app
        envSlug: dev
        secretsPath: "/"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: default

## Identifier of the deployment (e.g. "ef00") which should serve the paths directly
## accessible from the `ingress.host` root like `/.well-known` and the app homepage.
mainDeployment: "default"

## Configure one or more named deployments to be hosted under `ingress.host`
deployments:
  ## Example deployment
  # ## Internal, unique identifier for deployment for reference by `mainDeployment` and
  # ## used as key prefix within Infisical.
  # ef00:
  #   ## (optional) Override version to be deployed (default: `global.version`).
  #   version: "3.6.0"
  #   ## Convention identifier (CID) used to route requests to this deployment.
  #   ## Schema:  https://<ingress.host>/<CID>/
  #   ## Exmaple: https://example.com/EF00/
  #   cid: "EF00"
  #   ## (optional) Override image configuration (default: `global.image`).
  #   image:
  #     repository: ghcr.io/eurofurence
  #     imagePullPolicy: Always
  #   ## Backend component providing the API endpoints
  #   backend:
  #     ## (optional) Optimise resource usage of deployment.
  #     ## (see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)
  #     resources:
  #       requests:
  #         memory: "64Mi"
  #         cpu: "50m"
  #       limits:
  #         memory: "512Mi"
  #         cpu: "1000m"
  #     ## (not needed when using Infisical) Reference to volume containing:
  #     ## - `appsettings.json`
  #     ##   (see https://github.com/eurofurence/ef-app_backend-dotnet-core/blob/main/src/Eurofurence.App.Server.Web/appsettings.sample.json)
  #     ## - `firebase.json`
  #     ##   (see https://github.com/eurofurence/ef-app_backend-dotnet-core/blob/main/src/Eurofurence.App.Server.Web/firebase.sample.json)
  #     ## (see https://kubernetes.io/docs/concepts/storage/volumes/)
  #     configVolume:
  #       secret:
  #         secretName: mobile-app-ef00-backend-config
  #   ## Backoffice component providing a web UI for convenient content management.
  #   backoffice:
  #     ## (optional) Optimise resource usage of deployment.
  #     ## (see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)
  #     resources:
  #       limits:
  #         cpu: "500m"
  #         memory: "512Mi"
  #       requests:
  #         cpu: "50m"
  #         memory: "64Mi"
  #     ## (not needed when using Infisical) Reference to volume containing:
  #     ## - `appsettings-backoffice.json`
  #     ##   (see https://github.com/eurofurence/ef-app_backend-dotnet-core/blob/main/src/Eurofurence.App.Backoffice/wwwroot/appsettings.sample.json)
  #     ## (see https://kubernetes.io/docs/concepts/storage/volumes/)
  #     configVolume:
  #       configMap:
  #         name: mobile-app-ef00-backoffice-config
  #   ## (not needed when using Infisical) Reference to volume containing:
  #   ## - `apple-app-site-association.json`
  #   ##   (see https://developer.apple.com/documentation/xcode/supporting-associated-domains)
  #   ## - `assetlinks.json`
  #   ##   (see https://developer.android.com/training/app-links/verify-android-applinks)
  #   ## (see https://kubernetes.io/docs/concepts/storage/volumes/)
  #   wellKnownVolume:
  #     configMap:
  #       name: mobile-app-ef00-well-known
