apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "critter.fullname" . }}
  labels:
    {{- include "critter.labels" . | nindent 4 }}
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "critter.fullname" . }}-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ include "critter.fullname" . }}-app
    spec:
      containers:
        - name: critter-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "critter.managedSecretReferenceSecretName" . }}
          volumeMounts:
            - mountPath: /var/www/config/config.php
              subPath: config.php
              name: config
          livenessProbe:
            httpGet:
              path: /health
              port: 80
      volumes:
        - name: config
          configMap:
            name: {{ include "critter.fullname" . }}-config
