apiVersion: v1
kind: Service
metadata:
  name: {{ include "critter.fullname" . }}-app
  labels:
    {{- include "critter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      name: http
  selector:
    app: {{ include "critter.fullname" . }}-app
