########################################################################
# argoCD Manifest for this project/application
########################################################################
project: fursuit-badges
source:
  repoURL: 'git@github.com:eurofurence/helm-charts.git'
  path: charts/laravel
  targetRevision: HEAD
  helm:
    # releaseName: fursuit-reg
    valueFiles:
      - values.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: ef-fursuit-badges-dev
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    - Replace=true
