{{- range $key, $value := .Values.deployments }}
{{- $deploymentName := ( include "ef-mobile-app.deploymentName" ( list $ $key ) ) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-backoffice" $deploymentName | quote }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}
spec:
  selector:
    app: {{ $deploymentName | quote }}
  ports:
    - port: 80
      targetPort: http-backoffice
      name: http
---
{{- end }}
